### ISSUE TITLE
java.lang.NoSuchFieldError: VERSION_FULL_COMPOUND when running saker build

### ISSUE THREAD

**Issue by unlimitedcoder2** [sakerbuild/saker.build#23]
**Describe the bug**
I was following the guide on how to publish packages to maven and the error occurred
**To Reproduce**
To reproduce follow [This](https://saker.build/blog/github_packages_maven/)
**Expected behavior**
It to successfully build the jar into `build/saker.jar.create/output.jar` 
**Environment information**
 - Operating System: Linux, Ubuntu 20.04
 - Build system full version: 0.8.0
 - Java runtime version:
   openjdk version "1.8.0_265"
   OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
   OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
 - IDE: Command Line

**Bug nature**
Build execution
$ java -jar saker.build.jar -bd build export
java.lang.NoSuchFieldError: VERSION_FULL_COMPOUND
	  at saker.build:9:14-79
	  at saker.build:7:11-152
	  at saker.build:7:2-152
	  at saker.build:4:1-182
	  at saker.build:20:11-26
	  at saker.build:20:11-33
	  at saker.build:20:2-33
	  at saker.build:17:1-173
	at saker.maven.classpath.main.MavenClassPathTaskFactory$1.run(MavenClassPathTaskFactory.java:99)
Exception in thread "main" saker.build.exception.BuildExecutionFailedException: saker.build.task.exception.MultiTaskExecutionFailedException: BuildTargetBootstrapperTaskIdentifier[buildFilePath=wd:/saker.build, buildTargetName=export, workingDirectory=wd:, buildDirectory=]
	at saker.build.launching.BuildCommand.runBuild(BuildCommand.java:661)
	at saker.build.launching.BuildCommand.call(BuildCommand.java:558)
	at saker.build.launching.Launcher.lambda$parse$1(Launcher.java:1404)
	at saker.build.launching.Launcher.callCommand(Launcher.java:1807)
	at saker.build.launching.Launcher.main(Launcher.java:1785)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at saker.build.launching.Main.main(Main.java:67)
**Build configuration**
https://github.com/Sipkab/example-gh-maven
cloned to https://github.com/unlimitedcoder2/example-gh-maven
so I could upload the package to gh maven

**Comment by Sipkab** [comment]
Thanks for the detailed bug report.

That article was published a while ago, and some incompatible changes were made to saker.build. I was able to reproduce your issue.
Please download the latest release by following [this guide](https://saker.build/saker.build/doc/installation.html).

I see you're on Ubuntu, this command will do fine:

```
curl -L https://api.nest.saker.build/bundle/download/saker.build-v0.8.15 -o saker.build.jar
```

**Comment by unlimitedcoder2** [comment]
Thanks
